# Generated by Django 5.1.5 on 2025-01-29 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_alter_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('course_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='instructor.course')),
            ],
        ),
    ]
